#
# This file is subject to the license terms in the LICENSE file found in the
# qa-browsertests top-level directory and at
# https://git.wikimedia.org/blob/qa%2Fbrowsertests/HEAD/LICENSE. No part of
# qa-browsertests, including this file, may be copied, modified, propagated, or
# distributed except according to the terms contained in the LICENSE file.
#
# Copyright 2012-2013 by the Mediawiki developers. See the CREDITS file in the
# qa-browsertests top-level directory and at
# https://git.wikimedia.org/blob/qa%2Fbrowsertests/HEAD/CREDITS
#
chrome:
  name: chrome
  platform: Linux
  version:

firefox:
  name: firefox
  platform: Linux
  version: 25

internet_explorer_6:
  name: internet_explorer
  platform: Windows XP
  version: 6

internet_explorer_7:
  name: internet_explorer
  platform: Windows XP
  version: 7

internet_explorer_8:
  name: internet_explorer
  platform: Windows XP
  version: 8

internet_explorer_9:
  name: internet_explorer
  platform: Windows 7
  version: 9

internet_explorer_10:
  name: internet_explorer
  platform: Windows 8
  version: 10
